FROM httpd:2.4
ADD  ./ProjectCert.war /usr/local/apache2/htdocs/
ADD  ./src/ /usr/local/apache2/htdocs/
COPY my.apache.conf /usr/local/apache2/conf/my.apache.conf
RUN echo "Include /usr/local/apache2/conf/my.apache.conf" \
    >> /usr/local/apache2/conf/httpd.conf
